# Generated by Django 4.1.4 on 2022-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesApp', '0002_message_subject_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
